alias ..="cd .."
alias ls='ls -h --group-directories-first --color=auto'
alias ll="ls -Al"
alias l="ls -l"
alias bis="beet import -s"
alias gss="git status -s"
alias grep="grep --ignore-case --color=auto"
alias t="tree -I node_modules -I vendor --dirsfirst"
alias tt="t -a"
alias clip="xclip -selection clipboard -i"
alias ende="trans en:de"
alias deen="trans de:en"
alias cat="bat"
alias hx="helix"
alias y="yt-dlp -o ~/Downloads/%(playlist)s/%(title)s.%(ext)s"
alias arch="ssh -t M700.local tmux new -As0"
