alias ..="cd .."
alias ls='ls -h --group-directories-first --color=auto'
alias ll="ls -Al"
alias l="ls -l"
alias bis="beet import -Asm"
alias gss="git status -s"
alias grep="grep --ignore-case --color=auto"
alias t="tree -I node_modules -I vendor --dirsfirst"
alias tt="t -a"
alias clip="xclip -selection clipboard -i"
alias ende="trans en:de"
alias deen="trans de:en"
alias cat="bat"
alias hx="helix"
alias arch="ssh -t m700 tmux new -As0"
alias x="startx ~/.xinitrc"
alias y="yt-dlp"
alias yl="yt-dlp -x https://music.youtube.com/playlist?list=LM -o '~/Downloads/likes/%(title)s.%(ext)s'"
