PGUP cycle dvbin-channel-switch-offset up ; playlist-prev; show-text "${playlist-pos-1}/${playlist-count}"
PGDWN cycle dvbin-channel-switch-offset down ; playlist-next; show-text "${playlist-pos-1}/${playlist-count}"
j cycle dvbin-channel-switch-offset up ; playlist-prev; show-text "${playlist-pos-1}/${playlist-count}"
k cycle dvbin-channel-switch-offset down ; playlist-next; show-text "${playlist-pos-1}/${playlist-count}"
